const CONTROL_PARAM_DEFS = [
  { key: 'particleCount', type: 'number', digits: 0 },
  { key: 'enableAutoRenderScale', type: 'bool' },
  { key: 'autoRenderScaleThresholdPx', type: 'number', digits: 0 },
  { key: 'particleSize', type: 'number', digits: 2 },
  { key: 'particleSizeRandomNegative', type: 'number', digits: 2 },
  { key: 'particleSizeRandomPositive', type: 'number', digits: 2 },
  { key: 'boxCollisionParticipantRatio', type: 'number', digits: 2 },
  { key: 'enableForegroundLayer', type: 'bool' },
  { key: 'showBackgroundCanvas', type: 'bool' },
  { key: 'showBackgroundCanvasB', type: 'bool' },
  { key: 'showForegroundCanvas', type: 'bool' },
  { key: 'enableDualInkLayers', type: 'bool' },
  { key: 'inkLayerPhaseOffset', type: 'number', digits: 2 },
  { key: 'foregroundTrailAlpha', type: 'number', digits: 0 },
  { key: 'foregroundParticleAlpha', type: 'number', digits: 0 },
  { key: 'foregroundWindMultiplier', type: 'number', digits: 2 },
  { key: 'particleRenderMinSpeed', type: 'number', digits: 2 },
  // display: readout format only — the stored value stays the raw coefficient.
  // These four are gains applied as (1 + boost * signal), so the panel shows
  // the resulting factor instead of the coefficient. See CONTROL_OUTPUT_FORMATTERS.
  { key: 'particleSpeedAlphaBoost', type: 'number', digits: 2, display: 'gainPerSpeed' },
  { key: 'particleDuneAlphaBoost', type: 'number', digits: 2, display: 'gainPeak' },
  { key: 'particleDuneSizeBoost', type: 'number', digits: 2, display: 'gainPeak' },
  { key: 'particleSpeedWidthBoost', type: 'number', digits: 2, display: 'gainPerSpeed' },
  { key: 'enableConstantInk', type: 'bool' },
  { key: 'constantInkExponent', type: 'number', digits: 2 },
  { key: 'particleRenderFraction', type: 'number', digits: 2 },
  { key: 'enableAdaptiveQuality', type: 'bool' },
  { key: 'lockQualityTier', type: 'bool' },
  { key: 'qualityTargetFps', type: 'number', digits: 0 },
  { key: 'qualityDecisionWindowMs', type: 'number', digits: 0 },
  { key: 'qualityCooldownMs', type: 'number', digits: 0 },
  { key: 'qualityTransitionMs', type: 'number', digits: 0 },
  { key: 'qualityHudEnabled', type: 'bool' },
  { key: 'pauseSimulation', type: 'bool' },
  { key: 'enableAmbientMotion', type: 'bool' },
  { key: 'enableDuneBands', type: 'bool' },
  { key: 'showDuneDebugLayer', type: 'bool' },
  { key: 'duneDebugOpacity', type: 'number', digits: 2 },
  { key: 'showFlowArrows', type: 'bool' },
  { key: 'flowArrowSpacing', type: 'number', digits: 0 },
  { key: 'flowArrowOpacity', type: 'number', digits: 2 },
  { key: 'ambientWindDirectionDeg', type: 'number', digits: 0, display: 'deg' },
  { key: 'ambientWindStrength', type: 'number', digits: 3 },
  { key: 'duneBandRotationDeg', type: 'number', digits: 0, display: 'deg' },
  { key: 'duneBandScale', type: 'number', digits: 0 },
  { key: 'duneBandOffsetPx', type: 'number', digits: 0 },
  { key: 'duneAlongWarpScale', type: 'number', digits: 0 },
  { key: 'duneWarpStrength', type: 'number', digits: 2 },
  { key: 'duneContrast', type: 'number', digits: 2 },
  { key: 'duneDriftSpeed', type: 'number', digits: 2 },
  { key: 'microNoiseScale', type: 'number', digits: 0 },
  { key: 'microTurbulenceStrength', type: 'number', digits: 3 },
  { key: 'flowFieldMix', type: 'number', digits: 2 },
  { key: 'curlStrength', type: 'number', digits: 3 },
  { key: 'curlNoiseScale', type: 'number', digits: 0 },
  { key: 'curlAngleRangeDeg', type: 'number', digits: 0 },
  { key: 'curlDriftSpeed', type: 'number', digits: 3 },
  { key: 'curlDuneModulation', type: 'number', digits: 2 },
  { key: 'equalizeNoiseTexture', type: 'bool' },
  { key: 'curlDivergenceFree', type: 'bool' },
  { key: 'curlAngleCalibrated', type: 'bool' },
  { key: 'curlCompressibility', type: 'number', digits: 2 },
  { key: 'curlDuneRibbon', type: 'number', digits: 2 },
  { key: 'duneRidgeAttraction', type: 'number', digits: 3 },
  { key: 'duneRidgeFalloff', type: 'number', digits: 2 },
  { key: 'respawnRandomizeVelocity', type: 'number', digits: 2 },
  { key: 'perParticleForceMultMax', type: 'number', digits: 2 },
  { key: 'perParticleVelMultMax', type: 'number', digits: 2 },
  { key: 'windBoostParticleRatio', type: 'number', digits: 3 },
  { key: 'windBoostSizeMultiplier', type: 'number', digits: 2 },
  { key: 'windBoostAlphaMultiplier', type: 'number', digits: 2 },
  { key: 'windBoostMinMultiplier', type: 'number', digits: 2 },
  { key: 'windBoostMaxMultiplier', type: 'number', digits: 2 },
  { key: 'windBoostTurbulenceMinMultiplier', type: 'number', digits: 2 },
  { key: 'windBoostTurbulenceMaxMultiplier', type: 'number', digits: 2 },
  { key: 'enableBoidFlocking', type: 'bool' },
  { key: 'boidNeighborRadius', type: 'number', digits: 0 },
  { key: 'boidSeparationRadius', type: 'number', digits: 0 },
  { key: 'boidSeparationStrength', type: 'number', digits: 2 },
  { key: 'boidAlignmentStrength', type: 'number', digits: 2 },
  { key: 'boidCohesionStrength', type: 'number', digits: 2 },
  { key: 'boidMaxSteerForce', type: 'number', digits: 3 },
  { key: 'boidWindBlend', type: 'number', digits: 2 },
  { key: 'boidMaxGroupSize', type: 'number', digits: 0 },
  { key: 'boidDispersalStrength', type: 'number', digits: 2 },
  { key: 'enableWordShadow', type: 'bool' },
  { key: 'wordShadowBlur', type: 'number', digits: 0 },
  { key: 'wordShadowOpacity', type: 'number', digits: 2 },
  { key: 'enableBoxInkErase', type: 'bool' },
  { key: 'boxInkEraseAlpha', type: 'number', digits: 0 },
  { key: 'boxInkErasePadding', type: 'number', digits: 0 },
  { key: 'boxInkEraseSoftness', type: 'number', digits: 0 },
  { key: 'enableBoxGlow', type: 'bool' },
  { key: 'boxGlowRadius', type: 'number', digits: 0 },
  { key: 'boxGlowHaloSize', type: 'number', digits: 1 },
  { key: 'boxGlowHaloAlpha', type: 'number', digits: 0 },
  { key: 'boxGlowCoreWhite', type: 'number', digits: 2 },
  { key: 'boxGlowCoreDiameter', type: 'number', digits: 1 },
  { key: 'boxGlowFadeDelayMs', type: 'number', digits: 0 },
  { key: 'boxGlowFadeDurationMs', type: 'number', digits: 0 },
  { key: 'glowBlendOklch', type: 'bool' },
  { key: 'glowBlendChromaFloor', type: 'number', digits: 3 },
  { key: 'glowBlendHueShift', type: 'number', digits: 1 },
  { key: 'edgeRespawnWeightBase', type: 'number', digits: 2 },
  { key: 'edgeRespawnWeightStrength', type: 'number', digits: 2 },
  { key: 'edgeRespawnWeightExponent', type: 'number', digits: 2 },
  { key: 'useWeightedEdgeRespawn', type: 'bool' },
  { key: 'edgeRespawnWeightedMixPercent', type: 'number', digits: 0 },
  { key: 'enableParticleSeparation', type: 'bool' },
  { key: 'particleCollisionRadius', type: 'number', digits: 2 },
  { key: 'particleCollisionStrength', type: 'number', digits: 2 },
  { key: 'particleCollisionVelocityDamp', type: 'number', digits: 2 },
  { key: 'separationEveryNFrames', type: 'number', digits: 0 },
  { key: 'separationNearBoxRadius', type: 'number', digits: 0 },
  { key: 'separationMinSpeed', type: 'number', digits: 2 },
  { key: 'boxForceMaxRadius', type: 'number', digits: 1 },
  { key: 'surfaceSlideBand', type: 'number', digits: 2 },
  { key: 'staticInfluenceForwardDotMin', type: 'number', digits: 2 },
  { key: 'backsideDragStrength', type: 'number', digits: 2 },
  { key: 'scrollFreezeDebounceMs', type: 'number', digits: 0 },
  { key: 'scrollFreezeFadeInMs', type: 'number', digits: 0 },
  { key: 'backgroundPulsePeriodSec', type: 'number', digits: 1 },
  { key: 'backgroundPulseCurveMaxY', type: 'number', digits: 2 },
];

const COLOR_PARAM_DEFS = [
  { key: 'fade', param: 'colorFade' },
  { key: 'particles', param: 'colorParticles' },
  { key: 'windBoostColor', param: 'colorWindBoost' },
  { key: 'separationZone', param: 'colorSeparationZone' },
  { key: 'boxStrokeIdle', param: 'colorBoxStrokeIdle' },
  { key: 'boxStrokeDragged', param: 'colorBoxStrokeDragged' },
  { key: 'boxGlowCore', param: 'colorBoxGlowCore' },
];

const COLOR_ALPHA_PARAM_DEFS = [
  { key: 'fade', param: 'colorFadeAlpha', source: 'config', configKey: 'trailAlpha', digits: 0 },
  { key: 'particles', param: 'colorParticlesAlpha', source: 'render', digits: 0 },
  { key: 'separationZone', param: 'colorSeparationZoneAlpha', source: 'config', configKey: 'separationZoneAlpha', digits: 0 },
  { key: 'boxStrokeIdle', param: 'colorBoxStrokeIdleAlpha', source: 'render', digits: 0 },
  { key: 'boxStrokeDragged', param: 'colorBoxStrokeDraggedAlpha', source: 'render', digits: 0 },
  { key: 'boxGlowCore', param: 'colorBoxGlowCoreAlpha', source: 'render', digits: 0 },
];
