const CONTROL_TOOLTIPS = {
  particleSize: 'Base thickness of particle strokes before random size variation and speed-based width boosts.',
  particleSizeRandomNegative: 'Maximum negative random size offset applied when a particle is spawned.',
  particleSizeRandomPositive: 'Maximum positive random size offset applied when a particle is spawned.',
  particleRenderMinSpeed: 'Particles below this speed are hidden. Just above this threshold, alpha ramps in smoothly.',
  particleSpeedAlphaBoost: 'Multiplies Particles Alpha by speed. The readout is the factor at 1px/frame of speed, so 2.20×/px means a particle moving 1px/frame is 2.2× as bright, and one moving 3px/frame is 4.6×. Speed is unbounded, so unlike the dune boost this has no ceiling of its own — only the 255 alpha clamp. 1.00×/px = off. Stacks multiplicatively with Dune Alpha Boost.',
  particleDuneAlphaBoost: 'Multiplies Particles Alpha by the dune signal, which is 0 in troughs and 1 on ridges. The readout is the ridge maximum, so 3.20× max means ridge particles reach 3.2× the base alpha while trough particles stay at 1×. Bounded, unlike the speed boost. 1.00× max = off.',
  particleDuneSizeBoost: 'Multiplies stroke weight by the dune signal, 0 in troughs to 1 on ridges. The readout is the ridge maximum, so 2.87× max means ridge strokes reach 2.87× Particle Size. 1.00× max = off. Stacks multiplicatively with Speed Width Boost.',
  particleSpeedWidthBoost: 'Multiplies stroke weight by speed. The readout is the factor at 1px/frame, so 2.17×/px means a particle moving 1px/frame draws 2.17× as thick. Unbounded like Speed Alpha Boost. 1.00×/px = off. Final weight snaps to the nearest 0.25px, so small changes may not show.',
  enableConstantInk: 'Makes stroke weight cost-neutral: whatever the size boosts do to a particle\'s width, its alpha is scaled the other way so it lays the same total ink. A stroke twice as wide covers twice the area, so it goes half as dark (or a quarter, at exponent 2). It works in both directions, so strokes thinner than Particle Size get brighter — Boosted Particles are 0.42× width by default and will noticeably brighten. Compares against the rendered weight after the 0.5px floor and 0.25px quantize, so particles pinned at the floor are left alone. The flat alpha add on boosted particles is not scaled.',
  constantInkExponent: 'How ink scales with width, when Constant Ink is on. 2 treats a particle as a disc — area goes as r², so tripling the radius drops alpha to a ninth, which is the strict "same ink" answer. 1 matches what actually gets painted: a stroked segment is a capsule, so its area is width × length and tripling the width only needs a third the alpha. 0 = off. Values above 2 over-correct and make big particles vanish.',
  particleRenderFraction:
    'Fraction of particles drawn. Below 1 the rest are skipped, not just dimmed — the tail ramp fades '
    + 'whatever sits nearest the cut, so what goes is always the faintest thing on screen. Instantly reversible: '
    + 'the skipped particles keep simulating.',
  particleSimFraction:
    'Fraction of particles simulated. Physics is about three quarters of frame time, so this is where a slow '
    + 'machine finds real headroom — but a dropped particle freezes where it stands and fades back in when it '
    + 'returns. Never goes below Render Fraction. Reach for this after Render Fraction, not before.',
  particleCount: 'Maximum particle budget used by the simulation and adaptive particle count system.',
  boxCollisionParticipantRatio: 'Fraction of particles that participate in poem collider box interactions.',
  enableAutoRenderScale: 'Automatically caps the internal canvas size on very large screens, then CSS stretches it to fill the viewport.',
  autoRenderScaleThresholdPx: 'Maximum internal canvas size before auto render scaling caps it.',
  maxPixelDensity:
    'Ceiling on the device pixel ratio all three canvases render at. 0 uses the display\'s own ratio. ' +
    'The main fill-rate control: on a Retina display, 1 quarters the pixels drawn each frame at the ' +
    'cost of sharpness in the trails. Changing it clears the accumulated ink.',
  edgeRespawnWeightBase: 'Base chance weight for edge respawn bins before dune influence is applied.',
  edgeRespawnWeightStrength: 'How strongly dune sampling biases random edge respawn locations.',
  edgeRespawnWeightExponent: 'Contrast of edge respawn weighting. Higher values favor high-weight bins more aggressively.',
  useWeightedEdgeRespawn: 'When enabled, all wrapped particles respawn using weighted edge distribution.',
  edgeRespawnWeightedMixPercent: 'Used only when weighted edge respawn is OFF. Percentage of wraps that still use weighted placement.',
  enableParticleSeparation: 'Enables particle-particle collision solving to prevent heavy overlap and clumping.',
  particleCollisionRadius: 'Distance at which particles begin separating from each other.',
  particleCollisionStrength: 'How strongly overlapping particles are pushed apart.',
  particleCollisionVelocityDamp: 'Velocity damping applied during separation impulses to reduce jitter and rebound.',
  separationEveryNFrames: 'Base interval for separation solves. Higher values reduce CPU cost but allow more temporary overlap.',
  separationNearBoxRadius: 'Activates separation for particles near collider boxes.',
  separationMinSpeed: 'Particles moving slower than this may skip separation unless near a box or recently interacted.',
  maxSeparationPairsPerTick: 'Hard cap on pair solves per update tick to bound worst-case CPU load.',
  maxSeparationCandidatesPerCell: 'Limits neighbor candidates checked per cell in dense regions for performance stability.',
  qualityTargetFps: 'The framerate adaptive quality steers toward. It trades detail against speed continuously until frame time matches this budget, so setting it higher means a thinner-looking field on a machine that cannot keep up.',
  enableAdaptiveQuality: 'Continuously trades detail for speed to hold Target FPS. Quality is a single 0-1 level, not a set of steps: it slides to wherever frame time meets the budget and stops there. Turning this off releases the level back to full quality.',
  lockQualityLevel: 'Freezes the quality level wherever it currently sits, so you can watch the framerate a given amount of detail actually costs without the controller moving underneath you.',
  qualityDegradeRate: 'How urgently quality drops when frames overrun. Measured in level units per second at double the frame budget, and scaled down proportionally as the overshoot shrinks — so a bad stall is caught in about a second while a near-miss barely moves. Raise it if stutters take too long to clear, lower it if a brief hitch visibly thins the field.',
  qualityRecoverRate: 'How quickly quality climbs back once there is headroom. Keep it well below the degrade rate: recovery is the direction that re-triggers the stutter, so a slow creep back settles, while a fast one pumps in and out.',
  qualityDeadband: 'How far over the frame budget things are allowed to run before quality starts dropping, as a fraction — 0.06 is 6% over. Widen it if normal frame-time jitter is nudging quality down. It only guards the degrade direction; recovery has none, so a machine with spare headroom always drifts back to full quality.',
  qualityTransitionMs: 'Smoothing on the effective budgets. This is only a jitter filter now that the quality level itself moves continuously — keep it short, since it is a second lag inside the control loop and long values make the controller hunt.',
  qualityHudEnabled: 'Shows a live on-screen performance HUD with FPS, quality level, and active budgets.',
  pauseSimulation: 'Pauses the flow simulation loop. The simulation also auto-pauses when the tab is hidden.',
  enableDuneBands: 'Turns dune band modulation on or off while leaving ambient wind and turbulence active.',
  enableAmbientMotion: 'Enables the ambient wind field and all motion forces. Disabling freezes particle movement.',
  ambientWindDirectionDeg: 'Sets the direction the ambient wind force pushes particles, in degrees.',
  ambientWindStrength: 'Overall strength of the ambient wind field.',
  duneBandRotationDeg: 'Rotates the dune band pattern independently from the wind direction, in degrees.',
  duneBandScale: 'Controls the spacing between large dune bands. Lower values create tighter banding.',
  duneBandOffsetPx: 'Shifts the dune band pattern across its own axis without changing angle or scale.',
  duneAlongWarpScale: 'Sets the length scale of the along-wind warp that bends the dune bands.',
  duneWarpStrength: 'How strongly the dune bands are warped and bent.',
  duneContrast: 'Increases or softens contrast between high-wind and low-wind dune bands.',
  duneDriftSpeed: 'How quickly the dune field drifts over time.',
  microNoiseScale: 'Spatial scale of the fine turbulence noise field. Larger values make broader, smoother noise.',
  microTurbulenceStrength: 'Strength of the fine-scale turbulent motion layered on top of the main wind.',
  windBoostParticleRatio: 'Fraction of particles assigned to the boosted subgroup.',
  windBoostSizeMultiplier: 'Size multiplier applied to boosted particles before other width boosts.',
  windBoostAlphaMultiplier: 'Despite the name this is additive, not a multiplier: a flat 0-255 alpha added to boosted particles after every multiplicative boost, so it lifts slow boosted particles too. 60 adds 60/255 of opacity.',
  windBoostMinMultiplier: 'Minimum wind-force multiplier for boosted particles.',
  windBoostMaxMultiplier: 'Maximum wind-force multiplier for boosted particles.',
  windBoostTurbulenceMinMultiplier: 'Minimum turbulence multiplier for boosted particles.',
  windBoostTurbulenceMaxMultiplier: 'Maximum turbulence multiplier for boosted particles.',
  enableBoidFlocking: 'Enables boid flocking (separation, alignment, cohesion) for boosted particles.',
  boidNeighborRadius: 'Perception radius for alignment and cohesion. Boosted particles within this distance are flock neighbors.',
  boidSeparationRadius: 'Distance below which boosted particles repel each other to avoid crowding.',
  boidSeparationStrength: 'How strongly boosted particles push apart when closer than the separation radius.',
  boidAlignmentStrength: 'How strongly boosted particles steer to match the average heading of nearby flock members.',
  boidCohesionStrength: 'How strongly boosted particles steer toward the center of mass of nearby flock members.',
  boidMaxSteerForce: 'Caps the magnitude of each individual boid steering vector before combining them.',
  boidWindBlend: 'Blends between boid forces (0) and wind/dune forces (1). 0.5 uses both equally.',
  boidMaxGroupSize: 'Preferred max neighbors. When a boid has more neighbors than this, cohesion flips to dispersal.',
  boidDispersalStrength: 'How strongly boids steer away from overcrowded groups.',
  enableBoxGlow: 'Gives particles near collision boxes a glow — halo in base color, white-hot center.',
  boxGlowRadius: 'How far from a box surface a particle can be and still glow. Intensity fades with distance.',
  boxGlowHaloSize: 'Multiplier for the halo stroke width relative to the normal particle stroke.',
  boxGlowHaloAlpha: 'Peak alpha of the halo glow at full intensity.',
  boxGlowCoreWhite: 'How much the particle core shifts toward the core color at full glow. 0 = no shift, 1 = full core color.',
  boxGlowCoreDiameter: 'Stroke diameter of the glowing core in pixels. Larger values make the core color more visible.',
  boxGlowFadeDelayMs: 'How long a particle holds full glow after leaving the box surface, in milliseconds.',
  boxGlowFadeDurationMs: 'How long the glow takes to fade out after the delay, in milliseconds.',
  enableGlowFlicker: 'Makes lit particles flicker like embers instead of holding a steady glow. Each particle gets its own noise phase, so they breathe independently rather than pulsing in lockstep. The flicker changes brightness and size only — halo alpha, core alpha and core width — and deliberately leaves the colour alone, so an ember stays its core colour as it dims instead of washing back toward the particle colour on every dip. Colour still cools back to normal as the glow itself fades, which is Fade Duration doing its job, not the flicker. It only ever subtracts, so turning it on can never make the glow brighter than it is now. Note it also affects the ink laid down: a flickering particle paints a beaded trail instead of a smooth one.',
  glowFlickerDepth: 'How much of the glow the flicker can take away at its darkest. 0 is off — identical to the flicker being disabled. 1 lets an ember wink out completely at the bottom of a dip. Because it only subtracts, raising this lowers average brightness as well as adding variation, so you will usually want to raise Core Alpha alongside it.',
  glowFlickerSpeed: 'How fast each ember breathes, in noise units per second. Perlin features are roughly one unit wide, so around 1 gives a slow flicker of about one dip per second and 10 or above reads as sparking. High speeds bead the deposited ink noticeably, since the particle is switching brightness faster than it moves.',
  glowBlendOklch: 'Uses OkLCh perceptual colour space for the glow blend instead of a plain RGB lerp. Keeps colours vivid and avoids passing through grey or white at the midpoint.',
  glowBlendChromaFloor: 'Minimum chroma (colour vividness) held during the OkLCh glow blend. Higher values prevent the transition from desaturating toward grey at the midpoint.',
  glowBlendHueShift: 'Rotates the glow core hue before blending, in degrees. Shifts which arc of the colour wheel the transition travels along.',
  boxForceMaxRadius: 'Maximum distance from a collider where box influence is allowed to affect particles.',
  surfaceSlideBand: 'Thickness of the near-surface band where particles are encouraged to slide along collider faces.',
  staticInfluenceForwardDotMin: 'Minimum forward alignment required before a moving box starts affecting nearby particles.',
  backsideDragStrength: 'How strongly particles are slowed on the lee side of a moving collider.',
  scrollFreezeDebounceMs: 'Delay in milliseconds before particle movement freezes during manual scroll. Higher values make the freeze less hair-trigger.',
  scrollFreezeFadeInMs: 'Duration in milliseconds for particles to fade back in after scroll interaction ends. 0 makes them reappear instantly.',
  backgroundPulsePeriodSec: 'Length of one background pulse cycle in seconds. The fade rests at its base alpha, then briefly spikes to erase accumulated trails. Set to 0 to disable.',
  backgroundPulseCurveMaxY: 'Vertical zoom for the Wipe Curve editor only: the alpha the top of the canvas represents. Lower values spread the useful low range over the full height so points are easier to place precisely. Keyframes keep their real alpha values, so changing this never alters the wipe — points above the ceiling pin to the top edge until you drag them back down.',
  enableWordShadow: 'When on, words cast a glyph-shaped drop shadow in the background color, visually separating the text from accumulated ink without any canvas work.',
  wordShadowBlur: 'Blur radius in pixels of the word drop shadow. A second layer at 2.5x this radius is added automatically for depth.',
  wordShadowOpacity: 'Opacity of the word drop shadow, 0 to 1.',
  flowFieldMix: 'Blend between the dune wind (0) and the curl noise flow field (1). At 0.5 both contribute equally to the final force.',
  curlStrength: 'Force magnitude of the curl flow field, comparable to Wind Strength.',
  curlNoiseScale: 'Pixels per noise unit for the curl field. Smaller values give tighter, busier swirls; larger values give broad sweeping curves.',
  curlAngleRangeDeg: 'Maximum deflection of the flow to either side of the wind direction, in degrees. 90 keeps all flow broadly downwind; 180 allows any direction. Applies in legacy curl mode, and in divergence-free mode only when Calibrate Angle Range is on — where it caps at 90, since past that no amount of curl can be bounded.',
  curlDriftSpeed: 'How fast the curl field morphs by drifting through noise space, in noise units per second. 0 freezes the pattern.',
  curlDuneModulation: 'How much the dune ridge value scales the curl force. At 1 the swirls inherit the dune banding; at 0 the curl field is uniform everywhere.',
  equalizeNoiseTexture: 'Spread the baked noise values uniformly across their range so the curl angle lerp uses its full configured range instead of clustering near the wind direction. Off = raw Perlin (bell-clustered, flow pins to the wind).',
  curlDivergenceFree: 'Use an incompressible curl-noise flow (curl of a noise potential) plus uniform wind. Prevents particles from collecting into filament bands over time. Off = legacy angle-from-noise curl, which uses Curl Angle Range and Curl Dune Modulation but tends to clump.',
  curlAngleCalibrated: 'Makes Curl Angle Range work in divergence-free mode, where the flow direction is normally whatever the noise gradient gives and cannot be steered. Clamping the angle per sample would reintroduce the convergence zones this mode exists to remove, so instead the curl is scaled so it is always shorter than the wind by exactly the amount that bounds the deflection — a constant gain, so the field stays truly divergence-free. While on, Curl Strength and Flow Field Mix no longer apply: the angle sets how far the flow bends and Wind Strength sets how fast it goes. Expect the field to run around wind speed, which is likely slower than an uncalibrated tune; raise Wind Strength to match. Typical deflection is about a fifth of the setting, since the bound is on the strongest point in the field, not the average. Micro Turbulence and Ridge Attraction are added afterward and can push past the bound.',
  curlCompressibility: 'Within curl-noise mode, blends from pure divergence-free curl (0 = no banding) toward the raw noise gradient (1 = full convergence banding). Dial in a little for some band structure without the full clumping. Tends to make spiral vortex traps.',
  showDuneDebugLayer: 'Diagnostic only, not part of the artwork. Paints the dune signal as greyscale over the whole scene: black in the troughs, white on the ridge crests. This is the exact value particles read for Dune Alpha Boost and Dune Size Boost, so white is where they brighten and widen. It drifts with Dune Drift Speed and reshapes with Band Scale, Rotation, Warp and Contrast, which makes it the quickest way to see what those are doing. With Dune Bands off it goes flat grey, since the wind is then uniform. Use Dune Field Opacity to fade it back against the particles.',
  duneDebugOpacity: 'Opacity of the dune debug field. 1.00 hides the scene behind an opaque map, useful for reading the band shape on its own; lower values let the particles show through so you can check they are gathering where the field says they should. No effect unless Show Dune Field is on.',
  showFlowArrows: 'Diagnostic only, not part of the artwork. Draws the total flow field as arrows over the scene: the same vector each particle is handed, so it includes wind, dune banding, ridge attraction, micro turbulence and the curl mix combined. Colour is alignment with the ambient wind — cyan runs downwind, amber crosswind, red upwind — so red immediately marks any pocket that drives particles backwards. Arrow length is relative to the strongest vector on screen, not absolute, so the plot stays readable at any wind strength.',
  flowArrowSpacing: 'Grid pitch of the flow arrows, in pixels. Tighten it to resolve small eddies, widen it to read the overall drift without the clutter. Cost scales with the square of the density, so halving this quadruples the arrow count.',
  flowArrowOpacity: 'Opacity of the flow arrows. Drop it when reading them on top of the dune field or against live particles. No effect unless Show Flow Arrows is on.',
  duneRidgeFalloff: 'Fades the ridge pull out as the dune field approaches white, so particles ease onto the flank instead of packing into the crest. 0 = the raw gradient, which still pulls at 60% of full strength where the debug field reads 0.9 white. Raising it moves the strongest pull down toward the dark side: 1 peaks at 0.25 grey, 2 at 0.15, 4 at 0.08. Peak strength is held constant, so this only changes where the pull acts, not how hard it pulls — no need to re-tune Ridge Attraction after moving it. No effect unless Ridge Attraction is above 0.',
  duneRidgeAttraction: 'Pulls particles sideways across the bands onto the dune ridges. The number is the peak sideways force as a fraction of wind strength, measured against the mean along-wind force: 0.10 is a gentle 0.14x, 0.25 is 0.34x, and the 0.50 top of the slider is 0.69x. Values above that are still reachable through the URL param but overpower the wind. Along-band flow is untouched, so particles gather into ribbons and keep travelling, instead of the point sinks Curl Compressibility creates. Use this for banding and leave Compressibility at 0. Independent of the curl field, so it works in either curl mode and at any Flow Field Mix. No effect when Dune Bands are off.',
  curlDuneRibbon: 'Scales the curl strength by the dune signal so flow slows in the troughs and particles pool there, forming ribbon bands aligned with the Dune Field ridges. 0 = uniform. Makes ribbons rather than the spiral traps of Compressibility.',
  respawnRandomizeVelocity: 'When a particle wraps at a screen edge, replace its velocity with a random one of this magnitude. Churns which particles sit in a band, but does not remove the band itself (those are field-locked) — keep low.',
  perParticleForceMultMax: 'Each particle gets a fixed random multiplier on how strongly the flow pushes it, drawn from 1 up to this value. Varies responsiveness/inertia so particles do not all track the same convergence lines. 1 = uniform.',
  perParticleVelMultMax: 'Each particle gets a fixed random multiplier on its speed, drawn from 1 up to this value. Same flow direction, different pace. 1 = uniform.',
  enableBoxInkErase: 'When on, word colliders continuously erase accumulated ink beneath them, carving clean channels through persistent trails.',
  boxInkEraseAlpha: 'Per-frame erase strength under each word. Higher values cut a crisp stencil instantly; lower values smudge ink away slowly.',
  boxInkErasePadding: 'Extra pixels of erase area beyond each word collider edge.',
  boxInkEraseSoftness: 'Width in pixels of the soft falloff at the erase edge. 0 gives a hard-edged cutout.',
  enableForegroundLayer: 'When on, word-colliding particles render to a separate overlay canvas with a fast transparent fade, while non-colliding particles keep laying persistent ink behind them.',
  showBackgroundCanvas: 'Show or hide ink canvas A. The simulation keeps running while hidden — use this to inspect each layer in isolation.',
  showBackgroundCanvasB: 'Show or hide ink canvas B (the phase-offset twin). The simulation keeps running while hidden.',
  enableDualInkLayers: 'When on, background ink alternates between two transparent canvases whose wipes are offset in time, so accumulated ink always survives somewhere on screen.',
  inkLayerPhaseOffset: 'How far through the pulse cycle canvas B runs ahead of canvas A. 0.5 wipes them at opposite times; 0 wipes both together.',
  showForegroundCanvas: 'Show or hide the foreground overlay canvas. The simulation keeps running while hidden — use this to inspect each layer in isolation.',
  foregroundTrailAlpha: 'How quickly foreground trails fade to transparent each frame. Higher values give shorter, snappier trails around the words.',
  foregroundParticleAlpha: 'Stroke alpha for foreground (word-colliding) particles. Independent of the background ink alpha.',
  foregroundWindMultiplier: 'Scales the flow force on foreground (word-colliding) particles only, letting the layer around the words run faster or slower than the ink behind it. 1.00 = off, 0 = the layer stops responding to the field and only drifts from collisions. It multiplies the whole sampled vector, so the direction is unchanged and curl, micro-turbulence and ridge pull scale along with the wind — the same way the boosted-particle wind multiplier works, and it stacks with that one. Does nothing while Foreground Layer is off, since those particles then fall through to the ink canvases.',
};

const COLOR_CONTROL_TOOLTIPS = {
  fade: 'Background clear or fade color used behind the particles.',
  particles: 'Base particle trail color.',
  windBoostColor: 'Color used for boosted particles instead of the base particle color.',
  separationZone: 'Debug color used for separation-zone visualization.',
  boxStrokeIdle: 'Outline color for collider boxes when idle.',
  boxStrokeDragged: 'Outline color for collider boxes while dragged.',
  boxGlowCore: 'Color that particle cores blend toward when glowing near collision boxes.',
};

const COLOR_ALPHA_CONTROL_TOOLTIPS = {
  fade: 'Alpha used for the background fade pass. Ignored when transparent trails are enabled.',
  particles: 'Base particle alpha before speed and trail fade adjustments.',
  separationZone: 'Opacity of the separation-zone debug overlay.',
  boxStrokeIdle: 'Opacity of idle collider box outlines.',
  boxStrokeDragged: 'Opacity of dragged collider box outlines.',
  boxGlowCore: 'Opacity of the glow core color applied to particles near collision boxes.',
};
