#!/usr/bin/env node
// Generates show/index.html from index.html.
//
// Generated, not copied. The argument against a stripped show build was that it
// would diverge from the build being tested; a copy has exactly that problem one
// step removed, since it goes stale the moment index.html changes. This script
// is the single edit point, `--check` fails if the output is out of date, and
// the show page loads the same ../src/js files as the tuning page — so the only
// difference between them is what is absent.
//
//   node tools/build-show.js          write show/index.html
//   node tools/build-show.js --check  exit 1 if it is stale
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'index.html');
const OUT_DIR = path.join(ROOT, 'show');
const OUT = path.join(OUT_DIR, 'index.html');

// Cut a well-delimited element out by name. Both targets are unique in the
// document (asserted below), so index-of is exact rather than a guess at HTML
// parsing — and if either ever stops being unique, this throws instead of
// quietly emitting a half-stripped page.
function cutElement(html, openMarker, closeTag) {
  const start = html.indexOf(openMarker);
  if (start === -1) throw new Error(`build-show: could not find ${openMarker}`);
  if (html.indexOf(openMarker, start + 1) !== -1) {
    throw new Error(`build-show: ${openMarker} is no longer unique`);
  }
  const end = html.indexOf(closeTag, start);
  if (end === -1) throw new Error(`build-show: no ${closeTag} after ${openMarker}`);
  const lineStart = html.lastIndexOf('\n', start) + 1;
  return html.slice(0, lineStart) + html.slice(end + closeTag.length).replace(/^[ \t]*\n/, '');
}

function build() {
  const source = fs.readFileSync(SRC, 'utf8');
  const sourceHash = crypto.createHash('sha256').update(source).digest('hex').slice(0, 16);

  // 0. Drop HTML comments. Mostly tidiness, but it also removes the commented-out
  //    ./dist/js/*.min.js block, which names a functions.min.js that has never
  //    existed — dead references are exactly what the asset check below is for,
  //    and there is no reason to carry a decoy into the show build.
  let html = source.replace(/<!--[\s\S]*?-->\n?/g, '');

  // 1. Remove the control panel and the pause button outright. Hiding the panel
  //    with display:none is what the non-debug path already does, and it is not
  //    enough: every input inside it stays in the document, reachable by Tab and
  //    by a stray touch, and still wired to live CONFIG.
  html = cutElement(html, '<aside id="dune-controls"', '</aside>');
  html = cutElement(html, '<button id="simulation-pause-toggle"', '</button>');

  // 2. Re-root asset paths one directory up. Not just src/href attributes —
  //    the inline @font-face block uses url("./src/fonts/...") and matching only
  //    attributes silently 404s Cinzel, which is the kind of failure that shows
  //    up as "the poem is in the wrong typeface" ten minutes before doors.
  //    The lookbehind keeps an already-rewritten ../src/ from becoming .../src/.
  html = html.replace(/(?<!\.)\.\/(src|dist)\//g, '../$1/');

  // 3. Load the hardening ahead of everything else, synchronously. Deferred
  //    would be too late: it has to clear the query string and swap localStorage
  //    before the inline font-size script and before any deferred app script.
  const inject = [
    '  <!-- Show-build hardening. Must run before every other script on the page. -->',
    '  <script src="../src/js/constants/showConfig.js"></script>',
    '  <script src="../src/js/show.js"></script>',
    '',
  ].join('\n');
  const bodyAt = html.indexOf('<body>');
  if (bodyAt === -1) throw new Error('build-show: no <body>');
  const afterBody = bodyAt + '<body>'.length;
  html = html.slice(0, afterBody) + '\n' + inject + html.slice(afterBody).replace(/^\n/, '');

  // 4. Stamp it, so a human opening the file knows not to hand-edit it and
  //    --check has something to compare.
  const banner = [
    '<!--',
    '  GENERATED by tools/build-show.js — do not edit.',
    '  Rebuild with: npm run build:show',
    `  source: index.html @ sha256:${sourceHash}`,
    '-->',
  ].join('\n');
  html = html.replace(/^<!doctype html>/i, (m) => `${m}\n${banner}`);
  if (!html.includes(banner)) html = banner + '\n' + html;

  return { html, sourceHash };
}

const { html } = build();
const check = process.argv.includes('--check');

if (check) {
  const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (existing === html) {
    console.log('show/index.html is up to date');
    process.exit(0);
  }
  console.error('show/index.html is STALE — run: npm run build:show');
  process.exit(1);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, html);

// Cheap self-checks on the emitted page, so a bad strip fails the build rather
// than shipping a show page with live controls in it.
const problems = [];
if (html.includes('data-key=')) problems.push('control inputs survived the strip');
// The bare string 'dune-controls' also appears as a localStorage key prefix in
// the inline font-size script, which is not markup — match the element instead.
if (html.includes('id="dune-controls"')) problems.push('panel markup survived the strip');
if (html.includes('id="simulation-pause-toggle"')) problems.push('pause button survived the strip');
const stray = html.match(/(?<!\.)\.\/(src|dist)\//g);
if (stray) problems.push(`${stray.length} unrewritten ./ path(s)`);
// Every local asset the page names must actually exist at that path from show/.
for (const m of html.matchAll(/(?:src|href)="(\.\.\/[^"]+)"|url\("(\.\.\/[^"]+)"\)/g)) {
  const rel = m[1] || m[2];
  if (!fs.existsSync(path.join(OUT_DIR, rel))) problems.push(`missing asset ${rel}`);
}
if (html.indexOf('show.js') > html.indexOf('flowField.js')) problems.push('show.js loads too late');
if (problems.length) {
  console.error('build-show: ' + problems.join('; '));
  process.exit(1);
}

const srcBytes = fs.statSync(SRC).size;
const outBytes = fs.statSync(OUT).size;
console.log(`show/index.html written  ${srcBytes} -> ${outBytes} bytes ` +
  `(${(100 - (outBytes / srcBytes) * 100).toFixed(1)}% of the page was control panel)`);
